### ISSUE TITLE
Project still alive

### ISSUE THREAD

**Issue by fritzvd** [infomark-org/infomark#17]
Hi :wave: 

We're redeveloping some curriculum for the HAN University of Applied Sciences in Arnhem and are busy investigating some options. GDPR-compliant applications are preferred :wink:.

At the moment everything runs and compiles, but I don't see anything. My guess is that I need to move the ui build somewhere in the infomark project. Is it possible to get in contact with someone to get it working?

Fritz

**Comment by PatWie** [comment]
Missing updates usually does not mean not alive :-)

Yes you will not see any ui as the ui is handled in a different repository if you compile it yourself. (The releases should have the UI though.)

You will need to copy those files similar to what the following lines do

https://github.com/infomark-org/infomark/blob/master/.drone.yml#L89-L99

The steps would be:
1. Build the UI from the separate git repository
2. Copy those generated output files into the [`static`](https://github.com/infomark-org/infomark/tree/master/static) folder in this git repo
3. Compile this repository

**Comment by PatWie** [comment]
I did re-run all unit tests and bumped the dependency versions. Unfortunately, we are still blocked by
```
	// https://github.com/jmoiron/sqlx/issues/755
	// https://github.com/jmoiron/sqlx/pull/754
```
